---
settings:
  name: NetApp solutions for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Soluciones para SAP
    url: "/index.html"
  - title: Qué hay de nuevo
    url: "/whats-new.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
