---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Soluciones SAP
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Soluciones SAP de FlexPod
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: Soluciones NetApp
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: Avisos legales
    url: "/legal-notices.html"
