---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Soluciones SAP
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: Soluciones SAP de FlexPod
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: Soluciones NetApp
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: Avisos legales
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: Mejores prácticas de configuración
    links:
    - title: Vídeos y demostraciones
      url: sap-bp-videos.html
    - title: Blogs
      url: sap-bp-blogs.html
    - title: Herramientas
      url: sap-bp-tools.html
  - title: Backup, restauración y recuperación ante desastres
    links:
    - title: Vídeos y demostraciones
      url: sap-dr-videos.html
    - title: Blogs
      url: sap-dr-blogs.html
    - title: Herramientas
      url: sap-dr-tools.html
  - title: Gestión del ciclo de vida
    links:
    - title: Vídeos y demostraciones
      url: sap-lcm-videos.html
    - title: Blogs
      url: sap-lcm-blogs.html
    - title: Herramientas
      url: sap-lcm-tools.html
  - title: Todas las soluciones SAP
    links:
    - title: Novedades
      url: sap-whatsnew.html
    - title: Vídeos y demostraciones
      url: sap-videos.html
    - title: Blogs
      url: sap-blogs.html
