---
sidebar: sidebar 
permalink: sap-dr-videos.html 
summary: Serie de vídeos y demostraciones donde se habla sobre backup, restauración y recuperación ante desastres de SAP 
keywords: netapp, solutions, SAP, backup, restore, disaster recover, dr, videos, demos 
---
= Vídeos y demostraciones de backup, restauración y recuperación ante desastres de SAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descripción general de vídeos y demostraciones en los que se destacan las soluciones de backup, restauración y recuperación ante desastres de SAP.



=== Vídeos y demostraciones de backup, restauración y recuperación ante desastres de SAP

* link:https://media.netapp.com/video-detail/6b94b9c3-0862-5da8-8332-5aa1ffe86419/disaster-recovery-options-for-sap-hana["Opciones de recuperación ante desastres para SAP HANA"^]


.Instalación y configuración DB2 Plugin, copia de seguridad de la base de datos DB2
video::66c87afd-ca53-4af1-8bd8-b2b900c1fb0f[panopto,width=360]
.Restauración y recuperación de la base de datos DB2
video::3a82e561-e5a2-4a23-9465-b2b900c1fac5[panopto,width=360]
.Instalación del complemento ASE, complemento de configuración ASE, backup de base de datos ASE
video::079554d1-452c-42e5-95f6-b2b900c1fa86[panopto,width=360]
.Restaurar y recuperar la base de datos de ASE
video::0aba8433-e0d0-4c40-be0a-b2b900c1fb54[panopto,width=360]