---
sidebar: sidebar 
permalink: backup/amazon-fsx-overview.html 
keywords: tr4926, 4926, introduction, overview 
summary: Este informe técnico proporciona las mejores prácticas para la protección de datos de SAP HANA en Amazon FSX para ONTAP de NetApp y SnapCenter de NetApp. Este documento abarca conceptos de SnapCenter, recomendaciones de configuración y flujos de trabajo de operaciones, incluidos la configuración, las operaciones de backup y operaciones de restauración y recuperación. 
---
= TR-4926: SAP HANA en Amazon FSX para ONTAP de NetApp: Backup y recuperación de datos con SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este informe técnico proporciona las mejores prácticas para la protección de datos de SAP HANA en Amazon FSX para ONTAP de NetApp y SnapCenter de NetApp. Este documento abarca conceptos de SnapCenter, recomendaciones de configuración y flujos de trabajo de operaciones, incluidos la configuración, las operaciones de backup y operaciones de restauración y recuperación.

Autor: Nils Bauer, NetApp

Las empresas requieren hoy en día una disponibilidad continua e ininterrumpida para sus aplicaciones SAP. Esperan niveles de rendimiento constantes frente al creciente volumen de datos, así como la necesidad de realizar tareas de mantenimiento rutinarias, como los backups del sistema. La realización de backups de bases de datos SAP es una tarea crucial y puede tener un efecto significativo en el rendimiento del sistema SAP de producción.

Los períodos definidos para los procesos de backup se reducen, mientras que la cantidad total de datos objeto de backup es cada vez mayor. Por lo tanto, es difícil encontrar una hora en la que se pueden realizar backups con un efecto mínimo en los procesos empresariales. El tiempo necesario para restaurar y recuperar los sistemas SAP es una preocupación, ya que deben minimizarse el tiempo de inactividad para la producción SAP y los sistemas que no son de producción para reducir los costes empresariales.
