---
sidebar: sidebar 
permalink: backup/anf-cba-overview.html 
keywords: tr4959, 4959, overview, introduction 
summary: 'Este informe técnico proporciona las mejores prácticas para la protección de datos de SAP HANA en Azure NetApp Files (ANF) con NetApp BlueXP Cloud Backup for Applications (CBA). El documento trata conceptos de CBA, prácticas recomendadas de configuración y descripciones de los flujos de trabajo de operaciones para operaciones de backup, restauración y recuperación.' 
---
= TR-4959: SAP HANA en ANF - Backup y recuperación con Cloud Backup para aplicaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Nils Bauer: NetApp

[role="lead"]
Este informe técnico proporciona las mejores prácticas para la protección de datos de SAP HANA en Azure NetApp Files (ANF) con NetApp BlueXP Cloud Backup for Applications (CBA). El documento trata conceptos de CBA, prácticas recomendadas de configuración y descripciones de los flujos de trabajo de operaciones para operaciones de backup, restauración y recuperación.

Las empresas requieren hoy en día una disponibilidad continua e ininterrumpida para sus aplicaciones SAP. Esperan niveles de rendimiento constantes frente al creciente volumen de datos y las tareas de mantenimiento rutinarias, como los backups del sistema. La realización de backups de bases de datos SAP es una tarea crucial y puede tener un efecto significativo en el rendimiento del sistema SAP de producción.

Los períodos definidos para los procesos de backup se reducen, mientras que la cantidad total de datos objeto de backup es cada vez mayor. Por lo tanto, es difícil encontrar un momento en el que se pueden realizar backups con un efecto mínimo en los procesos empresariales. El tiempo necesario para restaurar y recuperar los sistemas SAP es una preocupación, ya que deben minimizarse el tiempo de inactividad para la producción SAP y los sistemas que no son de producción para reducir los costes empresariales.

link:anf-cba-backup-and-recovery-using-azure-netapp-files.html["Siguiente: Backup y recuperación de datos con Azure NetApp Files."]
