---
sidebar: sidebar 
permalink: backup/hana-hycl-backup-info-version.html 
keywords: BlueXP, SAP HANA, restore 
summary: Esta sección enumera dónde encontrar información adicional y muestra el historial de versiones. 
---
= Información Adicional e Historial de Versiones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Dónde encontrar información adicional

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Backup y recuperación de datos de NetApp BlueXP Documentación de producto +
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protect-app-data-to-cloud.html["Proteja los datos de sus aplicaciones locales | Documentación de NetApp"]
* Backup y recuperación de datos de SAP HANA con SnapCenter +
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html#the-netapp-solution[]




== Historial de versiones

[cols="17%,23%,60%"]
|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Marzo de 2024 | Versión inicial 
|===
Consulte la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad (IMT)"] En el sitio de soporte de NetApp, con el fin de validar que las versiones exactas del producto y las funciones descritas en este documento son compatibles con su entorno concreto. La cabina IMT de NetApp define los componentes y las versiones del producto que pueden utilizarse para crear configuraciones que sean compatibles con NetApp. Los resultados específicos dependen de la instalación que realice cada cliente de acuerdo con las especificaciones publicadas.
