---
sidebar: sidebar 
permalink: backup/saphana-br-scs-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional e historial de versiones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-br-scs-advanced-configuration-and-tuning.html["Anterior: Configuración y ajuste avanzados."]

Si quiere más información sobre el contenido de este documento, consulte los siguientes documentos o sitios web:

* Página de recursos de SnapCenter
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx["https://www.netapp.com/us/documentation/snapcenter-software.aspx"^]

* Documentación del software SnapCenter
+
https://docs.netapp.com/us-en/snapcenter/index.html["https://docs.netapp.com/us-en/snapcenter/index.html"^]

* TR-4667: Automatización de copias del sistema SAP mediante SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf"^]

* TR-4719: Replicación de sistemas SAP HANA, backup y recuperación de datos con SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf"^]

* TR-4018: Integración de los sistemas ONTAP de NetApp con SAP Landscape Management
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf"^]

* TR-4646: Recuperación ante desastres de SAP HANA con replicación de almacenamiento
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf["https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Julio de 2017  a| 
* Versión inicial.




| Versión 1.1 | Septiembre de 2017  a| 
* Se añadió la sección “Configuración y ajuste avanzados”.
* Correcciones menores.




| Versión 2.0 | Marzo de 2018  a| 
* Actualizaciones para cubrir SnapCenter 4.0: Nuevo recurso de volumen de datos funcionamiento mejorado de Single File SnapRestore




| Versión 3.0 | Enero de 2020  a| 
* Añadió la sección “conceptos y mejores prácticas de SnapCenter”.
* Actualizaciones para cubrir SnapCenter 4.3: Detección automática restauración y recuperación de datos Soporte de HANA MDC varios inquilinos operación de restauración de un solo inquilino




| Versión 3.1 | Julio de 2020  a| 
* Actualizaciones y correcciones menores: Compatibilidad con NFSv4 con SnapCenter 4.3.1 Configuración de la implementación del complemento central de comunicación SSL para Linux en IBM Power




| Versión 3.2 | Noviembre de 2020  a| 
* Se añadieron los privilegios de usuario de la base de datos necesarios para HANA 2.0 SPS5.




| Versión 3.3 | Mayo de 2021  a| 
* Se ha actualizado la sección de configuración de SSL hdbsql.
* Se añadió el soporte LVM de Linux.




| Versión 3.4 | Agosto de 2021  a| 
* Se añadió la descripción de la configuración Deshabilitar la detección automática.




| Versión 3.5 | Febrero de 2022  a| 
* Actualizaciones menores para cubrir SnapCenter 4.6 y la compatibilidad con la detección automática para sistemas HANA con replicación de sistemas HANA.


|===