---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-install-prep-nfsv4.html 
keywords: sap, hana, installation, preparations, nfsv4, user, authentication, storage, controller, hosts 
summary: 'La versión 4 y posteriores de NFS requieren la autenticación de usuario. Esta autenticación se puede lograr mediante una herramienta de gestión de usuarios central, como un servidor de protocolo ligero de acceso a directorios (LDAP) o con cuentas de usuarios locales.' 
---
= Preparación de la instalación de SAP HANA para NFSv4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La versión 4 y posteriores de NFS requieren la autenticación de usuario. Esta autenticación se puede lograr mediante una herramienta de gestión de usuarios central, como un servidor de protocolo ligero de acceso a directorios (LDAP) o con cuentas de usuarios locales. En las siguientes secciones se describe cómo configurar las cuentas de usuario locales.

Los usuarios de administración `<sid>adm`,`<sid>crypt` y `sapsys` el grupo deben crearse manualmente en los hosts SAP HANA y en las controladoras de almacenamiento antes de que se inicie la instalación del software SAP HANA.



== Hosts SAP HANA

Si no existe, el `sapsys` El grupo debe crearse en el host SAP HANA. Debe seleccionarse un ID de grupo único que no entra en conflicto con los ID de grupo existentes en las controladoras de almacenamiento.

Los usuarios `<sid>adm` y `<sid>crypt` se crean en el host SAP HANA. Se deben seleccionar ID únicos que no entren en conflicto con los ID de usuario existentes en las controladoras de almacenamiento.

Para un sistema SAP HANA de varios hosts, los ID de usuario y de grupo deben ser los mismos en todos los hosts SAP HANA. El grupo y el usuario se crean en los otros hosts SAP HANA copiando las líneas afectadas dentro `/etc/group` y `/etc/passwd` desde el sistema de origen en todos los demás hosts SAP HANA.


NOTE: El dominio NFSv4 debe configurarse con el mismo valor en todos los servidores Linux  `/etc/idmapd.conf`) Y SVM. Establezca el parámetro de dominio “dominio = <domain-name>” en el archivo `/etc/idmapd.conf` Para los hosts Linux.

Habilite e inicie el servicio NFS IDMAPD.

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: Los kernels más recientes de Linux no requieren este paso. Los mensajes de advertencia pueden ignorarse de forma segura.



== Controladoras de almacenamiento

Los ID de usuario y el ID de grupo deben ser los mismos en los hosts SAP HANA y en las controladoras de almacenamiento. El grupo y el usuario se crean introduciendo los siguientes comandos en el clúster de almacenamiento:

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
Además, establezca el identificador de grupo de la raíz del usuario UNIX de la SVM en 0.

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....