---
sidebar: sidebar 
permalink: bp/hana-fas-fc-additional-info.html 
keywords: additional, information, sap, hana, fc 
summary: Para obtener más información acerca de la información descrita en este documento, consulte los siguientes documentos o sitios web. 
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* link:../index.html["Soluciones de software SAP HANA"^]
* link:../backup/hana-dr-sr-pdf-link.html["Recuperación ante desastres de SAP HANA con replicación de almacenamiento"^]
* link:../backup/hana-sc-generic-scope.html["Backup y recuperación de datos de SAP HANA con SnapCenter"^]
* link:../lifecycle/sc-copy-clone-introduction.html["Automatización de copias del sistema SAP mediante el complemento SAP HANA de SnapCenter"^]
* Centros de documentación de NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Hardware de almacenamiento empresarial certificado de SAP para SAP HANA
+
https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/["https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/"^]

* Requisitos de almacenamiento SAP HANA
+
https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html["https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html"^]

* Integración del centro de datos a medida de SAP HANA
+
https://help.sap.com/docs/SAP_HANA_PLATFORM/eb3777d5495d46c5b2fa773206bbfb46/0b15a92d554c4941a452c9ca127f8c70.html["https://help.sap.com/docs/SAP_HANA_PLATFORM/eb3777d5495d46c5b2fa773206bbfb46/0b15a92d554c4941a452c9ca127f8c70.html"^]

* SAP HANA en VMware vSphere Wiki
+
https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html["https://help.sap.com/docs/SUPPORT_CONTENT/virtualization/3362185751.html"^]

* Guía de prácticas recomendadas de SAP HANA en VMware vSphere
+
https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper["https://www.vmware.com/docs/sap_hana_on_vmware_vsphere_best_practices_guide-white-paper"^]


