---
sidebar: sidebar 
permalink: bp/hana-asa-fc-io-stack-configuration.html 
keywords: io, i/o, stack, configuration, database 
summary: A partir de SAP HANA 1.0 SPS10, SAP introdujo parámetros para ajustar el comportamiento de I/o y optimizar la base de datos para el sistema de archivos y almacenamiento utilizado. 
---
= Configuración de pila I/o para SAP HANA
:allow-uri-read: 




== Configuración de pila I/o para SAP HANA

A partir de SAP HANA 1.0 SPS10, SAP introdujo parámetros para ajustar el comportamiento de I/o y optimizar la base de datos para el sistema de archivos y almacenamiento utilizado.

NetApp ha realizado pruebas de rendimiento para definir los valores ideales. En la siguiente tabla se enumeran los valores óptimos tal como se han deducido de las pruebas de rendimiento.

|===
| Parámetro | Valor 


| max_parallel_io_requests | 128 


| async_read_submit | encendido 


| async_write_submit_active | encendido 


| async_write_submit_blocks | todo 
|===
Para SAP HANA 1.0 a SPS12, estos parámetros se pueden establecer durante la instalación de la base de datos SAP HANA, como se describe en la nota de SAP https://launchpad.support.sap.com/["2267798 – Configuración de la base de datos SAP HANA durante la instalación mediante hdbparam"^].

Como alternativa, los parámetros se pueden establecer después de la instalación de la base de datos SAP HANA mediante el `hdbparam` marco.

....
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.max_parallel_io_requests=128
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_active=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_read_submit=on
FC5adm@sapcc-hana-tst:/usr/sap/FC5/HDB00> hdbparam --paramset fileio.async_write_submit_blocks=all
....
A partir de SAP HANA 2.0, `hdbparam` queda obsoleto y los parámetros se mueven al `global.ini` archivo. Los parámetros pueden configurarse usando comandos SQL o SAP HANA Studio. Para obtener más información, consulte la nota de SAP https://launchpad.support.sap.com/["2399079: Eliminación de hdbparam en el HANA 2"^]. Los parámetros también se pueden establecer dentro de la `global.ini` archivo.

....
FC5adm@sapcc-hana-tst: /usr/sap/FC5/SYS/global/hdb/custom/config> cat global.ini
…
[fileio]
async_read_submit = on
async_write_submit_active = on
max_parallel_io_requests = 128
async_write_submit_blocks = all
…
....
Para SAP HANA 2.0 SPS5 y versiones posteriores, utilice `setParameter.py` script para establecer los parámetros correctos.

....
fc5adm@sapcc-hana-tst-03:/usr/sap/FC5/HDB00/exe/python_support>
python setParameter.py -set=SYSTEM/global.ini/fileio/max_parallel_io_requests=128
python setParameter.py -set=SYSTEM/global.ini/fileio/async_read_submit=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_active=on
python setParameter.py -set=SYSTEM/global.ini/fileio/async_write_submit_blocks=all
....