---
sidebar: sidebar 
permalink: bp/hana-fas-fc-host-setup_single_host.html 
keywords: configure, multipathing, create, lvm, volume, groups, logical, mount, points, file, systems 
summary: La documentación también contiene información sobre las configuraciones de multivía específicas de la versión de Linux utilizada. 
---
= Configuración de un solo host
:allow-uri-read: 




== Configuración de un solo host

[role="lead"]
Este capítulo describe la configuración de un único host SAP HANA utilizando Linux LVM.



== Configuración de LUN para sistemas de host único de SAP HANA

En el host SAP HANA, es necesario crear y montar grupos de volúmenes y volúmenes lógicos, como se indica en la siguiente tabla.

|===
| Volumen lógico/LUN | Punto de montaje en el host SAP HANA | Nota 


| LV: FC5_data_mnt0000-vol | /hana/datos/FC51/mnt00001 | Montado usando la entrada /etc/fstab 


| LV: FC5_log_mnt00001-vol | /hana/log/FC5/mnt00001 | Montado usando la entrada /etc/fstab 


| LUN: FC5_shared | /hana/shared/FC5 | Montado usando la entrada /etc/fstab 
|===

NOTE: Con la configuración descrita, el `/usr/sap/FC5` El directorio en el que se almacena el directorio de inicio predeterminado del usuario FC5adm está en el disco local.  En una configuración de recuperación ante desastres con replicación basada en disco, NetApp recomienda crear un LUN adicional dentro del `FC5_shared` volumen para el `/usr/sap/FC5` directorio para que todos los sistemas de archivos estén en el almacenamiento central.



=== Cree grupos de volúmenes LVM y volúmenes lógicos

. Inicialice todas las LUN como volumen físico.
+
....
pvcreate /dev/mapper/hana-FC5_data_mnt00001
pvcreate /dev/mapper/hana-FC5_data2_mnt00001
pvcreate /dev/mapper/hana-FC5_log_mnt00001
pvcreate /dev/mapper/hana-FC5_log2_mnt00001
....
. Cree los grupos de volúmenes para cada partición de registro y datos.
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/hana-FC5_data_mnt00001 /dev/mapper/hana-FC5_data2_mnt00001
vgcreate FC5_log_mnt00001 /dev/mapper/hana-FC5_log_mnt00001 /dev/mapper/hana-FC5_log2_mnt00001
....
. Cree un volumen lógico para cada partición de datos y registro. Utilice un tamaño de franja igual al número de LUN utilizadas por grupo de volúmenes (en este ejemplo, son dos) y un tamaño de franja de 256 k para datos y 64 000 para registro. SAP solo admite un volumen lógico por grupo de volúmenes.
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. Analice los volúmenes físicos, los grupos de volúmenes y los grupos de volúmenes en el resto de hosts.


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: Si estos comandos no encuentran los volúmenes, es necesario reiniciar.

Para montar los volúmenes lógicos, deben activarse los volúmenes lógicos. Para activar los volúmenes, ejecute el siguiente comando:

....
vgchange -a y
....


=== Crear sistemas de archivos

Cree el sistema de archivos XFS en todos los volúmenes lógicos de datos y registros y el LUN compartido de hana.

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/svm1-FC5_shared
....


=== Cree puntos de montaje

Cree los directorios de puntos de montaje necesarios y configure los permisos en el host de la base de datos:

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== Montaje de sistemas de archivos

Para montar sistemas de archivos durante el arranque del sistema utilizando el  `/etc/fstab` archivo de configuración, agregue los sistemas de archivos requeridos al  `/etc/fstab` archivo de configuración:

....
# cat /etc/fstab
/dev/mapper/hana-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....

NOTE: Los sistemas de archivos XFS para las LUN de datos y de registro deben montarse con el `relatime` y.. `inode64` las opciones de montaje.

Para montar los sistemas de archivos, ejecute el  `mount –a` comando en el host.
