---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_sap_hana_storage_connector_api.html 
keywords: api, failover, ha, high availability 
summary: Sólo se necesita un conector de almacenamiento en entornos de varios hosts que tengan capacidades de conmutación por error. En configuraciones de múltiples hosts, SAP HANA ofrece una funcionalidad de alta disponibilidad para que un host de base de datos de SAP HANA pueda conmutar al nodo de respaldo a un host de espera. En este caso, el host en espera accede a los LUN del host con error y los usa. 
---
= API del conector de almacenamiento SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Sólo se necesita un conector de almacenamiento en entornos de varios hosts que tengan capacidades de conmutación por error. En configuraciones de múltiples hosts, SAP HANA ofrece una funcionalidad de alta disponibilidad para que un host de base de datos de SAP HANA pueda conmutar al nodo de respaldo a un host de espera.

En este caso, el host en espera accede a los LUN del host con error y los usa. El conector de almacenamiento se utiliza para asegurarse de que sólo un host de base de datos puede acceder activamente a una partición de almacenamiento.

En las configuraciones de varios hosts de SAP HANA con almacenamiento de NetApp, se utiliza el conector de almacenamiento estándar proporcionado por SAP. La “Guía de administración del conector de almacenamiento de canal de fibra SAP HANA” se puede encontrar como un adjunto a. https://service.sap.com/sap/support/notes/1900823["Nota de SAP 1900823"^].
