---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_host_setup.html 
keywords: host, setup, configuration, parameter, enterprise, suse, linux, subdirectories, create, mount, points, file, systems 
summary: Todos los pasos descritos en esta sección son válidos tanto para los entornos SAP HANA en servidores físicos como para SAP HANA que se ejecuten en VMware vSphere. 
---
= Configuración del host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:saphana-fas-nfs_storage_controller_setup.html["Anterior: Configuración de la controladora de almacenamiento."]

Todos los pasos descritos en esta sección son válidos tanto para los entornos SAP HANA en servidores físicos como para SAP HANA que se ejecuten en VMware vSphere.



== Parámetro de configuración de SUSE Linux Enterprise Server

Cada host SAP HANA debe ajustar más parámetros del kernel y configuración para la carga de trabajo generada por SAP HANA.



=== SUSE Linux Enterprise Server 12 y 15

A partir de SUSE Linux Enterprise Server (SLES) 12 SP1, el parámetro kernel se debe establecer en un archivo de configuración del `/etc/sysctl.d` directorio. Por ejemplo, un archivo de configuración con el nombre `91-NetApp-HANA.conf` debe crearse.

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: Saptune, que se incluye en SLES para las versiones SAP OS, se puede utilizar para establecer estos valores. Consulte https://launchpad.support.sap.com/#/notes/3024346["Nota de SAP 3024346"^] (Requiere inicio de sesión SAP).

Si se utiliza NFSv3 para conectar el almacenamiento, el `sunrpc.tcp_max_slot_table_entries` el parámetro debe configurarse en `/etc/modprobe.d/sunrpc.conf`. Si el archivo no existe, primero debe crearse agregando la siguiente línea:

....
options sunrpc tcp_max_slot_table_entries=128
....


== Parámetro de configuración de Red Hat Enterprise Linux 7.2 o posterior

Debe ajustar más parámetros del kernel y de configuración en cada host SAP HANA para la carga de trabajo generada por SAP HANA.

Si se utiliza NFSv3 para conectar el almacenamiento, se debe configurar el parámetro `sunrpc.tcp_max_slot_table_entries` pulg `/etc/modprobe.d/sunrpc.conf`. Si el archivo no existe, primero debe crearlo agregando la siguiente línea:

....
options sunrpc tcp_max_slot_table_entries=128
....
A partir de Red Hat Enterprise Linux 7.2, debe configurar los parámetros del kernel en un archivo de configuración en el `/etc/sysctl.d` directorio. Por ejemplo, un archivo de configuración con el nombre `91-NetApp-HANA.conf` debe crearse.

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: Dado que RedHat Enterprise Linux versión 8.6, esta configuración también se puede aplicar utilizando los roles del sistema RHEL para SAP (Ansible). Consulte https://launchpad.support.sap.com/#/notes/3024346["Nota de SAP 3024346"^] (Requiere inicio de sesión SAP).



== Cree subdirectorios en /hana/shared volume


NOTE: Los ejemplos muestran una base de datos SAP HANA con SID=NF2.

Para crear los subdirectorios necesarios, realice una de las siguientes acciones:

* Para un sistema host único, monte el `/hana/shared` volume y cree el `shared` y.. `usr-sap` subdirectorios.


....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap
sapcc-hana-tst-06:mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....
* En el caso de un sistema con varios hosts, monte el `/hana/shared` volume y cree el `shared` y la `usr-sap` subdirectorios para cada host.
+
Los comandos de ejemplo muestran un sistema HANA de varios hosts 2+1.



....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host1
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host2
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host3
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....


== Cree puntos de montaje


NOTE: Los ejemplos muestran una base de datos SAP HANA con SID=NF2.

Para crear los directorios de puntos de montaje necesarios, realice una de las siguientes acciones:

* Para un sistema host único, cree puntos de montaje y establezca los permisos en el host de la base de datos.


....
sapcc-hana-tst-06:/ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/shared
sapcc-hana-tst-06:/ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/log/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/data/NF2
sapcc-hana-tst-06:/ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:/ # chmod -R 777 /usr/sap/NF2
....
* En el caso de un sistema host múltiple, cree puntos de montaje y establezca los permisos en todos los hosts de trabajo y en espera.
+
Los siguientes comandos de ejemplo son para un sistema HANA de 2+1 host múltiple.

+
** Primer trabajador anfitrión:




....
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/shared
sapcc-hana-tst-06:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:~ # chmod -R 777 /usr/sap/NF2
....
* Segundo trabajador anfitrión:


....
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/shared
sapcc-hana-tst-07:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-07:~ # chmod -R 777 /usr/sap/NF2
....
* Host en espera:


....
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/shared
sapcc-hana-tst-08:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-08:~ # chmod -R 777 /usr/sap/NF2
....


== Montaje de sistemas de archivos

Las diferentes opciones de montaje se usan en función de la versión de NFS y la versión de ONTAP. Deben montarse los siguientes sistemas de archivos en los hosts:

* `/hana/data/SID/mnt0000*`
* `/hana/log/SID/mnt0000*`
* `/hana/shared`
* `/usr/sap/SID`


La siguiente tabla muestra las versiones de NFS que deben utilizarse para los diferentes sistemas de archivos para bases de datos SAP HANA de un solo host y de varios hosts.

|===
| Sistemas de ficheros | Host SAP HANA único | SAP HANA varios hosts 


| /hana/data/SID/mnt0000* | NFSv3 o NFSv4 | NFSv4 


| /hana/log/SID/mnt0000* | NFSv3 o NFSv4 | NFSv4 


| /hana/shared | NFSv3 o NFSv4 | NFSv3 o NFSv4 


| /Usr/SAP/SID | NFSv3 o NFSv4 | NFSv3 o NFSv4 
|===
En la siguiente tabla se muestran las opciones de montaje para las distintas versiones de NFS y ONTAP. Los parámetros comunes son independientes de las versiones NFS y ONTAP.


NOTE: SAP Lama requiere que el directorio /usr/SAP/SID sea local. Por lo tanto, no monte un volumen de NFS para /usr/SAP/SID si utiliza SAP Lama.

En el caso de NFSv3, debe desactivar el bloqueo NFS para evitar las operaciones de limpieza de bloqueos de NFS si se produce un fallo en el servidor o el software.

Con ONTAP 9, el tamaño de transferencia de NFS se puede configurar hasta 1 MB. Concretamente, con las conexiones de 40 GbE o más rápidas al sistema de almacenamiento, debe configurar el tamaño de transferencia a 1 MB para alcanzar los valores de rendimiento esperados.

|===
| Parámetro común | NFSv3 | NFSv4 | Tamaño de transferencia de NFS con ONTAP 9 | Tamaño de transferencia de NFS con ONTAP 8 


| rw, bg, hard, timeo=600, noatime, | nfsvers=3,nolock, | nfsvers=4,1, bloqueo | rsize=1048576,wsize=262144, | rsize=65536,wsize=65536, 
|===

NOTE: Para mejorar el rendimiento de lectura con NFSv3, NetApp le recomienda utilizar `nconnect=n` mount Option, que está disponible con SUSE Linux Enterprise Server 12 SP4 o posterior y RedHat Enterprise Linux (RHEL) 8.3 o posterior.


NOTE: Las pruebas de rendimiento lo demuestran `nconnect=8` ofrece buenos resultados de lectura, especialmente para los volúmenes de datos. Las escrituras de registro pueden beneficiarse de un número menor de sesiones como, por ejemplo `nconnect=2`. Los volúmenes compartidos también pueden beneficiarse de la opción 'nconnect'. Tenga en cuenta que el primer montaje de un servidor NFS (dirección IP) define la cantidad de sesiones que se van a utilizar. Los demás montajes en la misma dirección IP no cambian esta opción aunque se utilice otro valor para nconnect.


NOTE: A partir de ONTAP 9.8 y SUSE SLES15SP2 o RedHat RHEL 8.4 o superior, NetApp admite también la opción nconnect para NFSv4.1. Para obtener información adicional, consulte la documentación del proveedor de Linux.

Para montar los sistemas de archivos durante el arranque del sistema con el `/etc/fstab` archivo de configuración, lleve a cabo los siguientes pasos:

El siguiente ejemplo muestra una única base de datos SAP HANA con SID=NF2 usando NFSv3 y un tamaño de transferencia NFS de 1 MB para lecturas y 256k para escrituras.

. Añada los sistemas de archivos necesarios al `/etc/fstab` archivo de configuración.
+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/usr-sap /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Ejecución `mount –a` para montar los sistemas de archivos en todos los hosts.


El siguiente ejemplo muestra una base de datos SAP HANA con varios hosts con SID=NF2 usando NFSv4.1 para sistemas de archivos de registro y datos, y NFSv3 para el `/hana/shared` y.. `/usr/sap/NF2` sistemas de ficheros: Se utiliza un tamaño de transferencia NFS de 1 MB para lecturas y 256 k para escrituras.

. Añada los sistemas de archivos necesarios al `/etc/fstab` archivo de configuración en todos los hosts.
+

NOTE: La `/usr/sap/NF2` el sistema de archivos es diferente para cada host de base de datos. El siguiente ejemplo muestra `/NF2_shared/usr- sap- host1`.

+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs  rw,nfsvers=4.1,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_data_mnt00002 /hana/data/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log02>:/NF2_log_mnt00002 /hana/log/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_shared/usr-sap-host1 /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data02>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=8,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Ejecución `mount –a` para montar los sistemas de archivos en todos los hosts.


link:saphana-fas-nfs_sap_hana_installation_preparations_for_nfsv4.html["Siguiente: Preparativos para la instalación de SAP HANA para NFSv4."]
