---
sidebar: sidebar 
permalink: bp/saphana_aff_fc_sap_hana_using_vmware_vsphere.html 
keywords:  
summary:  
---
= SAP HANA mediante VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existen varias opciones para conectar el almacenamiento a máquinas virtuales (VM). El preferido es conectar los volúmenes de almacenamiento con NFS directamente desde el sistema operativo invitado. Esta opción se describe en link:saphana_aff_nfs_introduction.html["SAP HANA en sistemas AFF de NetApp con NFS"].

También se admiten asignaciones de dispositivos sin formato (RDM), almacenes de datos FCP o almacenes de datos VVOL con FCP. Para ambas opciones de almacén de datos, solo se deben almacenar un volumen de registro o los datos SAP HANA en el almacén de datos para casos de uso productivos. Además, no puede implementarse el respaldo y la recuperación basados en Snapshot coordinado por SnapCenter y soluciones basadas en esto, como la clonación de sistemas SAP.

Para obtener más información sobre el uso de vSphere con SAP HANA, consulte los siguientes enlaces:

https://wiki.scn.sap.com/wiki/display/VIRTUALIZATION/SAP+HANA+on+VMware+vSphere["SAP HANA en VMware vSphere - virtualización - Wiki de la comunidad"^]

* http://www.vmware.com/files/pdf/SAP_HANA_on_vmware_vSphere_best_practices_guide.pdf["Prácticas recomendadas y recomendaciones para puestas en marcha de escalado vertical de SAP HANA en VMware vSphere"^]
* http://www.vmware.com/files/pdf/sap-hana-scale-out-deployments-on-vsphere.pdf["Prácticas recomendadas y recomendaciones para puestas en marcha de escalado horizontal de SAP HANA en VMware vSphere"^]
* https://launchpad.support.sap.com/["2161991 - Directrices de configuración de VMware vSphere - SAP ONE Support Launchpad (se requiere inicio de sesión)"^]

