---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_where_to_find_additional_information.html 
keywords: additional, information, fas, nfs, sap, hana 
summary: Para obtener más información acerca de la información descrita en este documento, consulte los siguientes documentos o sitios web. 
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Soluciones de software SAP HANA
+
https://www.netapp.com/sap-solutions/["https://www.netapp.com/sap-solutions/"^]

* TR-4646: Recuperación ante desastres de SAP HANA con replicación de almacenamiento
+
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-dr-sr_pdf_link.html["https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-dr-sr_pdf_link.html"^]

* TR-4614: Backup y recuperación de datos de SAP HANA con SnapCenter
+
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html["https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html"^]

* TR-4667: Automatización de copias del sistema SAP mediante el complemento SAP HANA de SnapCenter 4.0
+
https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html["https://docs.netapp.com/us-en/netapp-solutions-sap/lifecycle/sc-copy-clone-introduction.html"^]

* Centros de documentación de NetApp
+
https://www.netapp.com/support-and-training/documentation/["https://www.netapp.com/support-and-training/documentation/"^]

* Hardware de almacenamiento empresarial certificado de SAP para SAP HANA
+
http://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/enterprise-storage.html["http://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN/enterprise-storage.html"^]

* Requisitos de almacenamiento SAP HANA
+
https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html["https://www.sap.com/documents/2024/03/146274d3-ae7e-0010-bca6-c68f7e60039b.html"^]

* Preguntas frecuentes sobre la integración personalizada del centro de datos de SAP HANA
+
https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html["https://www.sap.com/documents/2016/05/e8705aae-717c-0010-82c7-eda71af511fa.html"^]

* Prácticas recomendadas de SAP HANA en VMware vSphere y guía de arquitectura de referencia
+
https://core.vmware.com/resource/sap-hana-vmware-vsphere-best-practices-and-reference-architecture-guide#introduction["https://core.vmware.com/resource/sap-hana-vmware-vsphere-best-practices-and-reference-architecture-guide#introduction"^]


