---
sidebar: sidebar 
permalink: lifecycle/lama-ansible-introduction.html 
keywords: tr4953, introduction, 4953, clone, copy, refresh automation 
summary: 'SAP Landscape Management (Lama) permite que los administradores de sistemas SAP automaticen las operaciones del sistema SAP, incluidas las operaciones completas de clonado, copia y actualización del sistema SAP.' 
---
= TR-4953: Integración de la gestión de entorno SAP de NetApp con Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SAP Landscape Management (Lama) permite que los administradores de sistemas SAP automaticen las operaciones del sistema SAP, incluidas las operaciones completas de clonado, copia y actualización del sistema SAP.

Autores: Michael Schlosser, Nils Bauer, NetApp

NetApp ofrece un amplio conjunto de módulos de Ansible que permite a SAP Lama acceder a tecnologías como Snapshot de NetApp y FlexClone a través de SAP Lama Automation Studio. Estas tecnologías ayudan a simplificar y acelerar las operaciones de clonado, copia y actualización de los sistemas SAP.

La integración puede la pueden utilizar los clientes que ejecuten soluciones de almacenamiento de NetApp en las instalaciones o los clientes que utilicen servicios de almacenamiento de NetApp en proveedores de cloud público como Amazon Web Services, Microsoft Azure o Google Cloud Platform.

Este documento describe la configuración de SAP Lama con funciones de almacenamiento de NetApp para obtener información sobre las operaciones de copia de sistemas SAP, clonado y actualización con la automatización de Ansible.
