---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:sc-copy-clone-sap-system-clone-with-snapcenter.html["Anterior: Clon del sistema SAP con SnapCenter."]

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* TR-4614: Backup y recuperación de datos de SAP HANA con SnapCenter
+
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html["https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html"^]

* https://www.netapp.com/us/media/tr-4018.pdf["TR-4018: Integración de los sistemas ONTAP de NetApp con SAP Landscape Management"^]
+
https://www.netapp.com/us/media/tr-4018.pdf["https://www.netapp.com/us/media/tr-4018.pdf"^]

* https://www.netapp.com/us/media/tr-4646.pdf["TR-4646: Recuperación ante desastres de SAP HANA con replicación de almacenamiento"^]
+
https://www.netapp.com/us/media/tr-4646.pdf["https://www.netapp.com/us/media/tr-4646.pdf"^]

* TR-4436: SAP HANA en sistemas All Flash FAS de NetApp con el protocolo Fibre Channel
+
https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_fc_introduction.html["https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_fc_introduction.html"^]

* TR-4435: SAP HANA en sistemas All Flash FAS de NetApp con NFS
+
https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html["https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html"^]

* Página de productos de las soluciones de software SAP de NetApp
+
http://www.netapp.com/us/solutions/applications/sap/index.aspx["http://www.netapp.com/us/solutions/applications/sap/index.aspx"^]





== Historial de versiones

|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Febrero de 2018 | Versión inicial. 


| Versión 2.0 | Febrero de 2021 | Reescriba la información que cubra SnapCenter 4.3 y las secuencias de comandos de automatización mejoradas. Nueva descripción de los flujos de trabajo para las operaciones de actualización del sistema y clonado del sistema. 


| Versión 3.0 | Mayo de 2022 | Flujo de trabajo actualizado para SnapCenter 4.6 P1. 
|===