---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-additional-info.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: Las soluciones de NetApp para optimizar la gestión del ciclo de vida de SAP están integradas en las herramientas de gestión del ciclo de vida y bases de datos de SAP HANA, combinando una protección eficiente de datos integrada en las aplicaciones con el aprovisionamiento flexible de sistemas de prueba de SAP. 
---
= Dónde encontrar información adicional e historial de versiones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* link:../index.html["Aplicaciones empresariales SAP y soluciones de bases de datos SAP HANA (netapp.com)"]
* link:../backup/hana-br-scs-overview.html["TR-4614: Backup y recuperación de datos de SAP HANA con SnapCenter"]
* link:../bp/hana-aff-fc-introduction.html["TR-4436: SAP HANA en sistemas All Flash FAS de NetApp con el protocolo Fibre Channel"]
* link:../bp/hana-aff-nfs-introduction.html["TR-4435: SAP HANA en sistemas All Flash FAS de NetApp con NFS"]
* link:../backup/fsxn-overview.html["TR-4926: SAP HANA en Amazon FSX para ONTAP de NetApp: Backup y recuperación de datos con SnapCenter"]
* link:lama-ansible-introduction.html["TR-4953: Integración de la gestión de entorno SAP de NetApp con Ansible"]
* link:libelle-sc-overview.html["TR-4929: Automatización de las operaciones de copia del sistema SAP con Libelle SystemCopy (netapp.com)"]
* link:../briefs/sap-alpaca-automation.html["Automatizando la copia del sistema SAP, la actualización y los flujos de trabajo clonados con ALPACA y NetApp SnapCenter"]
* link:../briefs/sap-avantra-automation.html["Automatización de la copia, la actualización y los flujos de trabajo de clonado con Avantra y NetApp SnapCenter"]


[cols="21%,20%,59%"]
|===
| Versión | Fecha | Historial de versiones del documento 


| Versión 1.0 | Febrero de 2018 | Versión inicial. 


| Versión 2.0 | Febrero de 2021  a| 
Reescriba la información que cubra SnapCenter 4.3 y las secuencias de comandos de automatización mejoradas. + Nueva descripción del flujo de trabajo para la actualización del sistema y las operaciones de clonación del sistema.



| Versión 3.0 | Mayo de 2022 | Adaptado al cambio de flujo de trabajo con SnapCenter 4,6 P1 


| Versión 4.0 | Julio de 2024  a| 
El documento cubre los sistemas NetApp en las instalaciones, FSX para ONTAP y Azure NetApp Files + Nueva SnapCenter 5,0 operaciones montadas y desmontadas durante la creación y eliminación de clones de flujos de trabajo + pasos específicos añadidos para SAN Fibre Channel + pasos específicos añadidos para Azure NetApp Files + script adaptado y simplificado `sc-system-refresh` + pasos necesarios incluidos para SAP HANA habilitado cifrado de volúmenes

|===