---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: Las soluciones de NetApp para optimizar la gestión del ciclo de vida de SAP están integradas en las herramientas de gestión del ciclo de vida y bases de datos de SAP HANA, combinando una protección eficiente de datos integrada en las aplicaciones con el aprovisionamiento flexible de sistemas de prueba de SAP. 
---
= Infraestructura y escenarios compatibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este documento describe las situaciones de clonación y actualización del sistema SAP para sistemas SAP HANA que se ejecutan en sistemas NetApp en las instalaciones, en los sistemas Amazon FSx para NetApp ONTAP y en Azure NetApp Files. Sin embargo, no todas las funciones y escenarios están disponibles en todas las plataformas de almacenamiento. La siguiente tabla resume las configuraciones compatibles.

Dentro del documento, utilizamos un entorno SAP HANA que se ejecuta en sistemas NetApp locales con NFS como protocolo de almacenamiento. La mayoría de los pasos del flujo de trabajo son idénticos en las diferentes plataformas y, si hay diferencias, se resaltan en este documento.

[cols="25%,25%,25%,25%"]
|===
|  | *Sistemas NetApp locales* | *AWS FSx para ONTAP de NetApp* | *Azure NetApp Files* 


| Protocolo de almacenamiento y sistema de archivos | Bare metal: NFS, FC con XFS VMware: montajes NFS in-guest, FC con VMDKs y XFS | NFS | NFS 


| Clonado ligero (FlexClone) | Sí | Sí | Sí, pero no está integrado en SnapCenter 


| Operación de división de clones | Sí | Sí | Sí, pero no está integrado en SnapCenter 


| Clonación desde el principal | Sí | Sí | Sí 


| Clonado desde backup externo | Sí | Sí | Sí, restaurar a un nuevo volumen desde un backup de ANF 


| Clonado en el sitio de recuperación ante desastres | Sí | Sí | Sí, pero no está integrado en SnapCenter 
|===
Información adicional sobre las operaciones de actualización del sistema SAP para HANA con VMware VMFS y sistemas NetApp ASAr2 la puedes encontrar en  https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["Actualización del sistema SAP"].
